# Generated by Django 5.0.1 on 2024-01-24 20:37

import test_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', storage=test_app.storage.NoReadFileSystemStorage(), upload_to='images/', width_field='width')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
